apiVersion: v1
kind: ConfigMap
metadata:
  name: blogo-config
data:
  blogo.yaml: |
    port: 8080
    log_level: info
    log_format: json
    fetch_on_start: true

    repos:
      - name: "System Design"
        url: "https://github.com/karanpratapsingh/system-design"
        type: single-md
        branch: main
        author: "Karan Pratap Singh"

      - name: "System Design Notes"
        url: "https://github.com/liquidslr/system-design-notes"
        type: multi-folder
        branch: main
        author: "liquidslr"
