apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blogo

commonLabels:
  app.kubernetes.io/name: blogo
  app.kubernetes.io/part-of: blogo

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - certificate.yaml
  - route.yaml

images:
  - name: quay.io/hclareth/blogo
    newTag: latest
